export interface Stock {
  symbol: string;
  name: string;
  exchange: string;
  type: string;
}

// Comprehensive list of IDX (Bursa Efek Indonesia) stocks - 500+ emiten
export const IDX_STOCKS: Stock[] = [
  // === PERBANKAN ===
  { symbol: "BBCA", name: "Bank Central Asia", exchange: "IDX", type: "stock" },
  { symbol: "BBRI", name: "Bank Rakyat Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "BMRI", name: "Bank Mandiri", exchange: "IDX", type: "stock" },
  { symbol: "BBNI", name: "Bank Negara Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "BRIS", name: "Bank Syariah Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "ARTO", name: "Bank Jago", exchange: "IDX", type: "stock" },
  { symbol: "BNLI", name: "Bank Permata", exchange: "IDX", type: "stock" },
  { symbol: "MEGA", name: "Bank Mega", exchange: "IDX", type: "stock" },
  { symbol: "NISP", name: "Bank OCBC NISP", exchange: "IDX", type: "stock" },
  { symbol: "BDMN", name: "Bank Danamon", exchange: "IDX", type: "stock" },
  { symbol: "BTPS", name: "Bank BTPN Syariah", exchange: "IDX", type: "stock" },
  { symbol: "BJTM", name: "Bank Jatim", exchange: "IDX", type: "stock" },
  { symbol: "BJBR", name: "Bank BJB", exchange: "IDX", type: "stock" },
  { symbol: "BNGA", name: "Bank CIMB Niaga", exchange: "IDX", type: "stock" },
  { symbol: "BTPN", name: "Bank BTPN", exchange: "IDX", type: "stock" },
  { symbol: "PNBN", name: "Bank Pan Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "BBTN", name: "Bank Tabungan Negara", exchange: "IDX", type: "stock" },
  { symbol: "BBKP", name: "Bank KB Bukopin", exchange: "IDX", type: "stock" },
  { symbol: "BBYB", name: "Bank Neo Commerce", exchange: "IDX", type: "stock" },
  { symbol: "BNBA", name: "Bank Bumi Arta", exchange: "IDX", type: "stock" },
  { symbol: "BMAS", name: "Bank Maspion", exchange: "IDX", type: "stock" },
  { symbol: "BSIM", name: "Bank Sinarmas", exchange: "IDX", type: "stock" },
  { symbol: "BVIC", name: "Bank Victoria International", exchange: "IDX", type: "stock" },
  { symbol: "BABP", name: "Bank MNC Internasional", exchange: "IDX", type: "stock" },
  { symbol: "AGRO", name: "Bank Raya Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "BGTG", name: "Bank Ganesha", exchange: "IDX", type: "stock" },
  { symbol: "BINA", name: "Bank Ina Perdana", exchange: "IDX", type: "stock" },
  { symbol: "DNAR", name: "Bank Oke Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "NOBU", name: "Bank Nationalnobu", exchange: "IDX", type: "stock" },
  { symbol: "SDRA", name: "Bank Woori Saudara", exchange: "IDX", type: "stock" },
  { symbol: "MCOR", name: "Bank China Construction Bank Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "AMAR", name: "Bank Amar Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "BKSW", name: "Bank QNB Indonesia", exchange: "IDX", type: "stock" },

  // === TELEKOMUNIKASI & TEKNOLOGI ===
  { symbol: "TLKM", name: "Telkom Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "GOTO", name: "GoTo Gojek Tokopedia", exchange: "IDX", type: "stock" },
  { symbol: "EMTK", name: "Elang Mahkota Teknologi", exchange: "IDX", type: "stock" },
  { symbol: "EXCL", name: "XL Axiata", exchange: "IDX", type: "stock" },
  { symbol: "ISAT", name: "Indosat Ooredoo Hutchison", exchange: "IDX", type: "stock" },
  { symbol: "BUKA", name: "Bukalapak.com", exchange: "IDX", type: "stock" },
  { symbol: "MTEL", name: "Dayamitra Telekomunikasi", exchange: "IDX", type: "stock" },
  { symbol: "TBIG", name: "Tower Bersama Infrastructure", exchange: "IDX", type: "stock" },
  { symbol: "TOWR", name: "Sarana Menara Nusantara", exchange: "IDX", type: "stock" },
  { symbol: "FREN", name: "Smartfren Telecom", exchange: "IDX", type: "stock" },
  { symbol: "BALI", name: "Bali Towerindo Sentra", exchange: "IDX", type: "stock" },
  { symbol: "DCII", name: "DCI Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "EDGE", name: "Indointernet", exchange: "IDX", type: "stock" },

  // === OTOMOTIF & ALAT BERAT ===
  { symbol: "ASII", name: "Astra International", exchange: "IDX", type: "stock" },
  { symbol: "UNTR", name: "United Tractors", exchange: "IDX", type: "stock" },
  { symbol: "AUTO", name: "Astra Otoparts", exchange: "IDX", type: "stock" },
  { symbol: "IMAS", name: "Indomobil Sukses Internasional", exchange: "IDX", type: "stock" },
  { symbol: "SMSM", name: "Selamat Sempurna", exchange: "IDX", type: "stock" },
  { symbol: "GJTL", name: "Gajah Tunggal", exchange: "IDX", type: "stock" },
  { symbol: "BRAM", name: "Indo Kordsa", exchange: "IDX", type: "stock" },
  { symbol: "INDS", name: "Indospring", exchange: "IDX", type: "stock" },
  { symbol: "LPIN", name: "Multi Prima Sejahtera", exchange: "IDX", type: "stock" },
  { symbol: "PRAS", name: "Prima Alloy Steel Universal", exchange: "IDX", type: "stock" },

  // === PERTAMBANGAN ===
  { symbol: "ADRO", name: "Adaro Energy", exchange: "IDX", type: "stock" },
  { symbol: "ANTM", name: "Aneka Tambang", exchange: "IDX", type: "stock" },
  { symbol: "PTBA", name: "Bukit Asam", exchange: "IDX", type: "stock" },
  { symbol: "MDKA", name: "Merdeka Copper Gold", exchange: "IDX", type: "stock" },
  { symbol: "INCO", name: "Vale Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "ITMG", name: "Indo Tambangraya Megah", exchange: "IDX", type: "stock" },
  { symbol: "HRUM", name: "Harum Energy", exchange: "IDX", type: "stock" },
  { symbol: "MEDC", name: "Medco Energi Internasional", exchange: "IDX", type: "stock" },
  { symbol: "AMMN", name: "Amman Mineral Internasional", exchange: "IDX", type: "stock" },
  { symbol: "MBMA", name: "Merdeka Battery Materials", exchange: "IDX", type: "stock" },
  { symbol: "BSSR", name: "Baramulti Suksessarana", exchange: "IDX", type: "stock" },
  { symbol: "DSSA", name: "Dian Swastatika Sentosa", exchange: "IDX", type: "stock" },
  { symbol: "GEMS", name: "Golden Energy Mines", exchange: "IDX", type: "stock" },
  { symbol: "TINS", name: "Timah", exchange: "IDX", type: "stock" },
  { symbol: "ZINC", name: "Kapuas Prima Coal", exchange: "IDX", type: "stock" },
  { symbol: "BYAN", name: "Bayan Resources", exchange: "IDX", type: "stock" },
  { symbol: "AADI", name: "Adaro Andalan Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "MYOH", name: "Samindo Resources", exchange: "IDX", type: "stock" },
  { symbol: "SMMT", name: "Golden Eagle Energy", exchange: "IDX", type: "stock" },
  { symbol: "DOID", name: "Delta Dunia Makmur", exchange: "IDX", type: "stock" },
  { symbol: "PSAB", name: "J Resources Asia Pasifik", exchange: "IDX", type: "stock" },
  { symbol: "ELSA", name: "Elnusa", exchange: "IDX", type: "stock" },
  { symbol: "ENRG", name: "Energi Mega Persada", exchange: "IDX", type: "stock" },
  { symbol: "RUIS", name: "Radiant Utama Interinsco", exchange: "IDX", type: "stock" },
  { symbol: "BORN", name: "Borneo Lumbung Energi", exchange: "IDX", type: "stock" },
  { symbol: "KKGI", name: "Resource Alam Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "FIRE", name: "Alfa Energi Investama", exchange: "IDX", type: "stock" },
  { symbol: "BOSS", name: "Borneo Olah Sarana Sukses", exchange: "IDX", type: "stock" },
  { symbol: "MBAP", name: "Mitrabara Adiperdana", exchange: "IDX", type: "stock" },
  { symbol: "PTRO", name: "Petrosea", exchange: "IDX", type: "stock" },

  // === ENERGI & GAS ===
  { symbol: "PGAS", name: "Perusahaan Gas Negara", exchange: "IDX", type: "stock" },
  { symbol: "ESSA", name: "Surya Esa Perkasa", exchange: "IDX", type: "stock" },
  { symbol: "PGEO", name: "Pertamina Geothermal Energy", exchange: "IDX", type: "stock" },
  { symbol: "BREN", name: "Barito Renewables", exchange: "IDX", type: "stock" },
  { symbol: "AKRA", name: "AKR Corporindo", exchange: "IDX", type: "stock" },
  { symbol: "RAJA", name: "Rukun Raharja", exchange: "IDX", type: "stock" },
  { symbol: "POWR", name: "Cikarang Listrindo", exchange: "IDX", type: "stock" },
  { symbol: "KEEN", name: "Kencana Energi Lestari", exchange: "IDX", type: "stock" },

  // === CONSUMER GOODS / FMCG ===
  { symbol: "UNVR", name: "Unilever Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "ICBP", name: "Indofood CBP", exchange: "IDX", type: "stock" },
  { symbol: "INDF", name: "Indofood Sukses Makmur", exchange: "IDX", type: "stock" },
  { symbol: "MYOR", name: "Mayora Indah", exchange: "IDX", type: "stock" },
  { symbol: "KLBF", name: "Kalbe Farma", exchange: "IDX", type: "stock" },
  { symbol: "SIDO", name: "Industri Jamu Sido Muncul", exchange: "IDX", type: "stock" },
  { symbol: "HMSP", name: "HM Sampoerna", exchange: "IDX", type: "stock" },
  { symbol: "GGRM", name: "Gudang Garam", exchange: "IDX", type: "stock" },
  { symbol: "CINT", name: "Chitose International", exchange: "IDX", type: "stock" },
  { symbol: "DLTA", name: "Delta Djakarta", exchange: "IDX", type: "stock" },
  { symbol: "DVLA", name: "Darya-Varia Laboratoria", exchange: "IDX", type: "stock" },
  { symbol: "KAEF", name: "Kimia Farma", exchange: "IDX", type: "stock" },
  { symbol: "KINO", name: "Kino Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "MLBI", name: "Multi Bintang Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "PYFA", name: "Pyridam Farma", exchange: "IDX", type: "stock" },
  { symbol: "ROTI", name: "Nippon Indosari Corpindo", exchange: "IDX", type: "stock" },
  { symbol: "SKBM", name: "Sekar Bumi", exchange: "IDX", type: "stock" },
  { symbol: "SKLT", name: "Sekar Laut", exchange: "IDX", type: "stock" },
  { symbol: "STTP", name: "Siantar Top", exchange: "IDX", type: "stock" },
  { symbol: "TCID", name: "Mandom Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "TSPC", name: "Tempo Scan Pacific", exchange: "IDX", type: "stock" },
  { symbol: "ULTJ", name: "Ultra Jaya Milk Industry", exchange: "IDX", type: "stock" },
  { symbol: "WIIM", name: "Wismilak Inti Makmur", exchange: "IDX", type: "stock" },
  { symbol: "GOOD", name: "Garudafood Putra Putri Jaya", exchange: "IDX", type: "stock" },
  { symbol: "ADES", name: "Akasha Wira International", exchange: "IDX", type: "stock" },
  { symbol: "ALTO", name: "Tri Banyan Tirta", exchange: "IDX", type: "stock" },
  { symbol: "CAMP", name: "Campina Ice Cream Industry", exchange: "IDX", type: "stock" },
  { symbol: "CEKA", name: "Wilmar Cahaya Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "CLEO", name: "Sariguna Primatirta", exchange: "IDX", type: "stock" },
  { symbol: "HOKI", name: "Buyung Poetra Sembada", exchange: "IDX", type: "stock" },
  { symbol: "KEJU", name: "Mulia Boga Raya", exchange: "IDX", type: "stock" },
  { symbol: "PANI", name: "Pratama Abadi Nusa Industri", exchange: "IDX", type: "stock" },
  { symbol: "PSGO", name: "Palma Serasih", exchange: "IDX", type: "stock" },

  // === PROPERTI & REAL ESTATE ===
  { symbol: "BSDE", name: "Bumi Serpong Damai", exchange: "IDX", type: "stock" },
  { symbol: "CTRA", name: "Ciputra Development", exchange: "IDX", type: "stock" },
  { symbol: "SMRA", name: "Summarecon Agung", exchange: "IDX", type: "stock" },
  { symbol: "PWON", name: "Pakuwon Jati", exchange: "IDX", type: "stock" },
  { symbol: "LPKR", name: "Lippo Karawaci", exchange: "IDX", type: "stock" },
  { symbol: "DILD", name: "Intiland Development", exchange: "IDX", type: "stock" },
  { symbol: "APLN", name: "Agung Podomoro Land", exchange: "IDX", type: "stock" },
  { symbol: "ASRI", name: "Alam Sutera Realty", exchange: "IDX", type: "stock" },
  { symbol: "KIJA", name: "Kawasan Industri Jababeka", exchange: "IDX", type: "stock" },
  { symbol: "MKPI", name: "Metropolitan Kentjana", exchange: "IDX", type: "stock" },
  { symbol: "SSIA", name: "Surya Semesta Internusa", exchange: "IDX", type: "stock" },
  { symbol: "DMAS", name: "Puradelta Lestari", exchange: "IDX", type: "stock" },
  { symbol: "PPRO", name: "PP Properti", exchange: "IDX", type: "stock" },
  { symbol: "MIKA", name: "Mitra Keluarga Karyasehat", exchange: "IDX", type: "stock" },
  { symbol: "PLIN", name: "Plaza Indonesia Realty", exchange: "IDX", type: "stock" },
  { symbol: "BEST", name: "Bekasi Fajar Industrial Estate", exchange: "IDX", type: "stock" },
  { symbol: "ELTY", name: "Bakrieland Development", exchange: "IDX", type: "stock" },
  { symbol: "GMTD", name: "Gowa Makassar Tourism Dev.", exchange: "IDX", type: "stock" },
  { symbol: "GPRA", name: "Perdana Gapuraprima", exchange: "IDX", type: "stock" },
  { symbol: "JRPT", name: "Jaya Real Property", exchange: "IDX", type: "stock" },
  { symbol: "MTLA", name: "Metropolitan Land", exchange: "IDX", type: "stock" },
  { symbol: "RDTX", name: "Roda Vivatex", exchange: "IDX", type: "stock" },
  { symbol: "NIRO", name: "Nirvana Development", exchange: "IDX", type: "stock" },
  { symbol: "URBN", name: "Urban Jakarta Propertindo", exchange: "IDX", type: "stock" },

  // === KONSTRUKSI & INFRASTRUKTUR ===
  { symbol: "WIKA", name: "Wijaya Karya", exchange: "IDX", type: "stock" },
  { symbol: "WSKT", name: "Waskita Karya", exchange: "IDX", type: "stock" },
  { symbol: "PTPP", name: "PP (Persero)", exchange: "IDX", type: "stock" },
  { symbol: "JSMR", name: "Jasa Marga", exchange: "IDX", type: "stock" },
  { symbol: "ADHI", name: "Adhi Karya", exchange: "IDX", type: "stock" },
  { symbol: "ACST", name: "Acset Indonusa", exchange: "IDX", type: "stock" },
  { symbol: "NRCA", name: "Nusa Raya Cipta", exchange: "IDX", type: "stock" },
  { symbol: "TOTL", name: "Total Bangun Persada", exchange: "IDX", type: "stock" },
  { symbol: "WTON", name: "Wijaya Karya Beton", exchange: "IDX", type: "stock" },
  { symbol: "DGIK", name: "Nusa Konstruksi Enjiniring", exchange: "IDX", type: "stock" },
  { symbol: "IDPR", name: "Indonesia Pondasi Raya", exchange: "IDX", type: "stock" },
  { symbol: "MTRA", name: "Mitra Pemuda", exchange: "IDX", type: "stock" },
  { symbol: "TOPS", name: "Totalindo Eka Persada", exchange: "IDX", type: "stock" },

  // === SEMEN & MATERIAL ===
  { symbol: "SMGR", name: "Semen Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "INTP", name: "Indocement Tunggal Prakarsa", exchange: "IDX", type: "stock" },
  { symbol: "SMCB", name: "Solusi Bangun Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "WSBP", name: "Waskita Beton Precast", exchange: "IDX", type: "stock" },
  { symbol: "SMBR", name: "Semen Baturaja", exchange: "IDX", type: "stock" },

  // === KIMIA & PETROKIMIA ===
  { symbol: "BRPT", name: "Barito Pacific", exchange: "IDX", type: "stock" },
  { symbol: "TPIA", name: "Chandra Asri Pacific", exchange: "IDX", type: "stock" },
  { symbol: "UNIC", name: "Unggul Indah Cahaya", exchange: "IDX", type: "stock" },
  { symbol: "DPNS", name: "Duta Pertiwi Nusantara", exchange: "IDX", type: "stock" },
  { symbol: "EKAD", name: "Ekadharma International", exchange: "IDX", type: "stock" },
  { symbol: "INCI", name: "Intanwijaya Internasional", exchange: "IDX", type: "stock" },
  { symbol: "MDKI", name: "Ecogreen Oleochemicals", exchange: "IDX", type: "stock" },
  { symbol: "MOLI", name: "Madusari Murni Indah", exchange: "IDX", type: "stock" },
  { symbol: "SRSN", name: "Indo Acidatama", exchange: "IDX", type: "stock" },
  { symbol: "TPIA", name: "Chandra Asri Pacific", exchange: "IDX", type: "stock" },

  // === PULP & KERTAS ===
  { symbol: "INKP", name: "Indah Kiat Pulp & Paper", exchange: "IDX", type: "stock" },
  { symbol: "TKIM", name: "Pabrik Kertas Tjiwi Kimia", exchange: "IDX", type: "stock" },
  { symbol: "FASW", name: "Fajar Surya Wisesa", exchange: "IDX", type: "stock" },
  { symbol: "ALDO", name: "Alkindo Naratama", exchange: "IDX", type: "stock" },
  { symbol: "KDSI", name: "Kedawung Setia Industrial", exchange: "IDX", type: "stock" },
  { symbol: "SPMA", name: "Suparma", exchange: "IDX", type: "stock" },

  // === PERKEBUNAN / CPO ===
  { symbol: "AALI", name: "Astra Agro Lestari", exchange: "IDX", type: "stock" },
  { symbol: "LSIP", name: "PP London Sumatra Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "SIMP", name: "Salim Ivomas Pratama", exchange: "IDX", type: "stock" },
  { symbol: "TBLA", name: "Tunas Baru Lampung", exchange: "IDX", type: "stock" },
  { symbol: "SGRO", name: "Sampoerna Agro", exchange: "IDX", type: "stock" },
  { symbol: "SSMS", name: "Sawit Sumbermas Sarana", exchange: "IDX", type: "stock" },
  { symbol: "DSNG", name: "Dharma Satya Nusantara", exchange: "IDX", type: "stock" },
  { symbol: "PALM", name: "Provident Agro", exchange: "IDX", type: "stock" },
  { symbol: "SMAR", name: "Smart", exchange: "IDX", type: "stock" },
  { symbol: "BWPT", name: "Eagle High Plantations", exchange: "IDX", type: "stock" },
  { symbol: "GZCO", name: "Gozco Plantations", exchange: "IDX", type: "stock" },
  { symbol: "JAWA", name: "Jaya Agra Wattie", exchange: "IDX", type: "stock" },
  { symbol: "MAGP", name: "Multi Agro Gemilang Plantation", exchange: "IDX", type: "stock" },
  { symbol: "TAPG", name: "Triputra Agro Persada", exchange: "IDX", type: "stock" },

  // === RETAIL & CONSUMER ===
  { symbol: "ERAA", name: "Erajaya Swasembada", exchange: "IDX", type: "stock" },
  { symbol: "ACES", name: "Ace Hardware Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "MAPI", name: "Mitra Adiperkasa", exchange: "IDX", type: "stock" },
  { symbol: "LPPF", name: "Matahari Department Store", exchange: "IDX", type: "stock" },
  { symbol: "AMRT", name: "Sumber Alfaria Trijaya", exchange: "IDX", type: "stock" },
  { symbol: "HERO", name: "Hero Supermarket", exchange: "IDX", type: "stock" },
  { symbol: "MIDI", name: "Midi Utama Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "RALS", name: "Ramayana Lestari Sentosa", exchange: "IDX", type: "stock" },
  { symbol: "CSAP", name: "Catur Sentosa Adiprana", exchange: "IDX", type: "stock" },
  { symbol: "DAYA", name: "Duta Intidaya", exchange: "IDX", type: "stock" },
  { symbol: "GLOB", name: "Globe Kita Terang", exchange: "IDX", type: "stock" },
  { symbol: "KPAL", name: "Steadfast Marine", exchange: "IDX", type: "stock" },
  { symbol: "MPPA", name: "Matahari Putra Prima", exchange: "IDX", type: "stock" },
  { symbol: "RANC", name: "Supra Boga Lestari", exchange: "IDX", type: "stock" },

  // === MEDIA & ENTERTAINMENT ===
  { symbol: "MNCN", name: "Media Nusantara Citra", exchange: "IDX", type: "stock" },
  { symbol: "SCMA", name: "Surya Citra Media", exchange: "IDX", type: "stock" },
  { symbol: "KPIG", name: "MNC Land", exchange: "IDX", type: "stock" },
  { symbol: "VIVA", name: "Visi Media Asia", exchange: "IDX", type: "stock" },
  { symbol: "JTPE", name: "Jasuindo Tiga Perkasa", exchange: "IDX", type: "stock" },
  { symbol: "FILM", name: "MD Pictures", exchange: "IDX", type: "stock" },

  // === LOGISTIK & TRANSPORTASI ===
  { symbol: "BIRD", name: "Blue Bird", exchange: "IDX", type: "stock" },
  { symbol: "GIAA", name: "Garuda Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "SMDR", name: "Samudera Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "TMAS", name: "Pelayaran Tempuran Emas", exchange: "IDX", type: "stock" },
  { symbol: "ASSA", name: "Adi Sarana Armada", exchange: "IDX", type: "stock" },
  { symbol: "TAXI", name: "Express Transindo Utama", exchange: "IDX", type: "stock" },
  { symbol: "HELI", name: "Jaya Trishindo", exchange: "IDX", type: "stock" },
  { symbol: "WEHA", name: "WEHA Transportasi Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "LRNA", name: "Eka Sari Lorena Transport", exchange: "IDX", type: "stock" },
  { symbol: "SAPX", name: "Satria Antaran Prima", exchange: "IDX", type: "stock" },
  { symbol: "JAYA", name: "Armada Berjaya Trans", exchange: "IDX", type: "stock" },
  { symbol: "CASS", name: "Cardig Aero Services", exchange: "IDX", type: "stock" },

  // === KESEHATAN ===
  { symbol: "HEAL", name: "Medikaloka Hermina", exchange: "IDX", type: "stock" },
  { symbol: "SILO", name: "Siloam International Hospitals", exchange: "IDX", type: "stock" },
  { symbol: "PRDA", name: "Prodia Widyahusada", exchange: "IDX", type: "stock" },
  { symbol: "MIKA", name: "Mitra Keluarga Karyasehat", exchange: "IDX", type: "stock" },
  { symbol: "SAME", name: "Sarana Meditama Metropolitan", exchange: "IDX", type: "stock" },
  { symbol: "CARE", name: "Metro Healthcare Indonesia", exchange: "IDX", type: "stock" },

  // === POULTRY & PETERNAKAN ===
  { symbol: "CPIN", name: "Charoen Pokphand Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "JPFA", name: "Japfa Comfeed Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "MAIN", name: "Malindo Feedmill", exchange: "IDX", type: "stock" },
  { symbol: "SIPD", name: "Sreeya Sewu Indonesia", exchange: "IDX", type: "stock" },

  // === TEKSTIL & GARMEN ===
  { symbol: "SRIL", name: "Sri Rejeki Isman", exchange: "IDX", type: "stock" },
  { symbol: "PBRX", name: "Pan Brothers", exchange: "IDX", type: "stock" },
  { symbol: "BELL", name: "Trisula Textile Industries", exchange: "IDX", type: "stock" },
  { symbol: "ERTX", name: "Eratex Djaja", exchange: "IDX", type: "stock" },
  { symbol: "RICY", name: "Ricky Putra Globalindo", exchange: "IDX", type: "stock" },
  { symbol: "STAR", name: "Buana Artha Anugerah", exchange: "IDX", type: "stock" },
  { symbol: "TRIS", name: "Trisula International", exchange: "IDX", type: "stock" },
  { symbol: "UNIT", name: "Nusantara Inti Corpora", exchange: "IDX", type: "stock" },

  // === KERAMIK & KACA ===
  { symbol: "AMFG", name: "Asahimas Flat Glass", exchange: "IDX", type: "stock" },
  { symbol: "ARNA", name: "Arwana Citramulia", exchange: "IDX", type: "stock" },
  { symbol: "CAKK", name: "Cahayaputra Asa Keramik", exchange: "IDX", type: "stock" },
  { symbol: "MARK", name: "Mark Dynamics Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "MLIA", name: "Mulia Industrindo", exchange: "IDX", type: "stock" },
  { symbol: "TOTO", name: "Surya Toto Indonesia", exchange: "IDX", type: "stock" },

  // === LOGAM & BAJA ===
  { symbol: "ISSP", name: "Steel Pipe Industry of Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "KRAS", name: "Krakatau Steel", exchange: "IDX", type: "stock" },
  { symbol: "INAI", name: "Indal Aluminium Industry", exchange: "IDX", type: "stock" },
  { symbol: "LION", name: "Lion Metal Works", exchange: "IDX", type: "stock" },
  { symbol: "NIKL", name: "Pelat Timah Nusantara", exchange: "IDX", type: "stock" },
  { symbol: "TBMS", name: "Tembaga Mulia Semanan", exchange: "IDX", type: "stock" },
  { symbol: "GDST", name: "Gunawan Dianjaya Steel", exchange: "IDX", type: "stock" },

  // === ASURANSI & FINANCE ===
  { symbol: "PNLF", name: "Panin Financial", exchange: "IDX", type: "stock" },
  { symbol: "LPGI", name: "Lippo General Insurance", exchange: "IDX", type: "stock" },
  { symbol: "ASRM", name: "Asuransi Ramayana", exchange: "IDX", type: "stock" },
  { symbol: "ASDM", name: "Asuransi Dayin Mitra", exchange: "IDX", type: "stock" },
  { symbol: "MFIN", name: "Mandala Multifinance", exchange: "IDX", type: "stock" },
  { symbol: "ADMF", name: "Adira Dinamika Multi Finance", exchange: "IDX", type: "stock" },
  { symbol: "BFIN", name: "BFI Finance Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "CFIN", name: "Clipan Finance Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "VRNA", name: "Verena Multi Finance", exchange: "IDX", type: "stock" },
  { symbol: "WOMF", name: "WOM Finance", exchange: "IDX", type: "stock" },
  { symbol: "HDFA", name: "Radana Bhaskara Finance", exchange: "IDX", type: "stock" },
  { symbol: "TRUS", name: "Trust Finance Indonesia", exchange: "IDX", type: "stock" },

  // === INVESTASI & HOLDING ===
  { symbol: "MLPL", name: "Multipolar", exchange: "IDX", type: "stock" },
  { symbol: "MPMX", name: "Mitra Pinasthika Mustika", exchange: "IDX", type: "stock" },
  { symbol: "PNIN", name: "Panin Insurance", exchange: "IDX", type: "stock" },
  { symbol: "BHIT", name: "MNC Investama", exchange: "IDX", type: "stock" },
  { symbol: "BNBR", name: "Bakrie & Brothers", exchange: "IDX", type: "stock" },
  { symbol: "SRTG", name: "Saratoga Investama Sedaya", exchange: "IDX", type: "stock" },
  { symbol: "LUCK", name: "Sentral Mitra Informatika", exchange: "IDX", type: "stock" },

  // === HOTEL & PARIWISATA ===
  { symbol: "HOTL", name: "Saraswati Griya Lestari", exchange: "IDX", type: "stock" },
  { symbol: "JSPT", name: "Jakarta Setiabudi Internasional", exchange: "IDX", type: "stock" },
  { symbol: "PDES", name: "Destinasi Tirta Nusantara", exchange: "IDX", type: "stock" },
  { symbol: "PSKT", name: "Red Planet Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "SHID", name: "Hotel Sahid Jaya International", exchange: "IDX", type: "stock" },
  { symbol: "MABA", name: "Marga Abhinaya Abadi", exchange: "IDX", type: "stock" },

  // === MAKANAN & RESTORAN ===
  { symbol: "FAST", name: "Fast Food Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "PZZA", name: "Sarimelati Kencana", exchange: "IDX", type: "stock" },
  { symbol: "MAPB", name: "MAP Boga Adiperkasa", exchange: "IDX", type: "stock" },
  { symbol: "BOGA", name: "Bintang Oto Global", exchange: "IDX", type: "stock" },
  { symbol: "JIND", name: "Jaya Industri Tbk", exchange: "IDX", type: "stock" },

  // === ELEKTRONIK & KOMPUTER ===
  { symbol: "MTDL", name: "Metrodata Electronics", exchange: "IDX", type: "stock" },
  { symbol: "LMAS", name: "Limas Indonesia Makmur", exchange: "IDX", type: "stock" },
  { symbol: "ZBRA", name: "Zebra Nusantara", exchange: "IDX", type: "stock" },

  // === SEKURITAS ===
  { symbol: "TRIM", name: "Trimegah Sekuritas Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "PANS", name: "Panin Sekuritas", exchange: "IDX", type: "stock" },
  { symbol: "KREN", name: "Kresna Graha Investama", exchange: "IDX", type: "stock" },
  { symbol: "APIC", name: "Pacific Strategic Financial", exchange: "IDX", type: "stock" },
  { symbol: "YULE", name: "Yulie Sekuritas Indonesia", exchange: "IDX", type: "stock" },

  // === PLASTIK & PACKAGING ===
  { symbol: "IMPC", name: "Impack Pratama Industri", exchange: "IDX", type: "stock" },
  { symbol: "AKPI", name: "Argha Karya Prima Industry", exchange: "IDX", type: "stock" },
  { symbol: "APLI", name: "Asiaplast Industries", exchange: "IDX", type: "stock" },
  { symbol: "BRNA", name: "Berlina", exchange: "IDX", type: "stock" },
  { symbol: "IGAR", name: "Champion Pacific Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "IPOL", name: "Indopoly Swakarsa Industry", exchange: "IDX", type: "stock" },
  { symbol: "TRST", name: "Trias Sentosa", exchange: "IDX", type: "stock" },
  { symbol: "YPAS", name: "Yana Prima Hasta Persada", exchange: "IDX", type: "stock" },

  // === PERIKANAN ===
  { symbol: "CPRO", name: "Central Proteina Prima", exchange: "IDX", type: "stock" },
  { symbol: "DSFI", name: "Dharma Samudera Fishing Industries", exchange: "IDX", type: "stock" },
  { symbol: "IIKP", name: "Inti Agri Resources", exchange: "IDX", type: "stock" },

  // === KABEL ===
  { symbol: "JECC", name: "Jembo Cable Company", exchange: "IDX", type: "stock" },
  { symbol: "KBLI", name: "KMI Wire and Cable", exchange: "IDX", type: "stock" },
  { symbol: "KBLM", name: "Kabelindo Murni", exchange: "IDX", type: "stock" },
  { symbol: "SCCO", name: "Supreme Cable Manufacturing & Commerce", exchange: "IDX", type: "stock" },
  { symbol: "VOKS", name: "Voksel Electric", exchange: "IDX", type: "stock" },

  // === PENDIDIKAN ===
  { symbol: "PRIM", name: "Royal Prima", exchange: "IDX", type: "stock" },

  // === PROPERTY MANAGEMENT ===
  { symbol: "MMLP", name: "Mega Manunggal Property", exchange: "IDX", type: "stock" },
  { symbol: "PAMG", name: "Bima Sakti Pertiwi", exchange: "IDX", type: "stock" },
  { symbol: "POLL", name: "Pollux Properti Indonesia", exchange: "IDX", type: "stock" },

  // === BARANG INDUSTRI ===
  { symbol: "ASAB", name: "Asuransi Astra Buana", exchange: "IDX", type: "stock" },
  { symbol: "GJTL", name: "Gajah Tunggal", exchange: "IDX", type: "stock" },
  { symbol: "MASA", name: "Multistrada Arah Sarana", exchange: "IDX", type: "stock" },

  // === TAMBAHAN EMITEN LAINNYA ===
  { symbol: "AISA", name: "Tiga Pilar Sejahtera Food", exchange: "IDX", type: "stock" },
  { symbol: "APEX", name: "Apexindo Pratama Duta", exchange: "IDX", type: "stock" },
  { symbol: "ARII", name: "Atlas Resources", exchange: "IDX", type: "stock" },
  { symbol: "ARMY", name: "Armidian Karyatama", exchange: "IDX", type: "stock" },
  { symbol: "ATAP", name: "Trimitra Prawara Goldland", exchange: "IDX", type: "stock" },
  { symbol: "BALI", name: "Bali Towerindo Sentra", exchange: "IDX", type: "stock" },
  { symbol: "BATA", name: "Sepatu Bata", exchange: "IDX", type: "stock" },
  { symbol: "BELL", name: "Trisula Textile Industries", exchange: "IDX", type: "stock" },
  { symbol: "BIPP", name: "Bhuwanatala Indah Permai", exchange: "IDX", type: "stock" },
  { symbol: "BISI", name: "BISI International", exchange: "IDX", type: "stock" },
  { symbol: "BKSL", name: "Sentul City", exchange: "IDX", type: "stock" },
  { symbol: "BMTR", name: "Global Mediacom", exchange: "IDX", type: "stock" },
  { symbol: "BOLT", name: "Garuda Metalindo", exchange: "IDX", type: "stock" },
  { symbol: "BUDI", name: "Budi Starch & Sweetener", exchange: "IDX", type: "stock" },
  { symbol: "BUKK", name: "Bukaka Teknik Utama", exchange: "IDX", type: "stock" },
  { symbol: "CBPE", name: "Cisarua Mountain Dairy", exchange: "IDX", type: "stock" },
  { symbol: "CLPI", name: "Colorpak Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "CMRY", name: "Cisarua Mountain Dairy", exchange: "IDX", type: "stock" },
  { symbol: "CMNP", name: "Citra Marga Nusaphala Persada", exchange: "IDX", type: "stock" },
  { symbol: "COWL", name: "Cowell Development", exchange: "IDX", type: "stock" },
  { symbol: "DART", name: "Duta Anggada Realty", exchange: "IDX", type: "stock" },
  { symbol: "DEWA", name: "Dewa United", exchange: "IDX", type: "stock" },
  { symbol: "DKFT", name: "Central Omega Resources", exchange: "IDX", type: "stock" },
  { symbol: "ERAL", name: "Eral Energi Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "ETWA", name: "Eterindo Wahanatama", exchange: "IDX", type: "stock" },
  { symbol: "FOOD", name: "Sentra Food Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "GEMA", name: "Gema Grahasarana", exchange: "IDX", type: "stock" },
  { symbol: "GOLD", name: "Visi Telekomunikasi Infrastruktur", exchange: "IDX", type: "stock" },
  { symbol: "HDTX", name: "Panasia Indo Resources", exchange: "IDX", type: "stock" },
  { symbol: "HITS", name: "Humpuss Intermoda Transportasi", exchange: "IDX", type: "stock" },
  { symbol: "IBST", name: "Inti Bangun Sejahtera", exchange: "IDX", type: "stock" },
  { symbol: "IFII", name: "Indonesia Fibreboard Industry", exchange: "IDX", type: "stock" },
  { symbol: "INAF", name: "Indofarma", exchange: "IDX", type: "stock" },
  { symbol: "INDY", name: "Indika Energy", exchange: "IDX", type: "stock" },
  { symbol: "IPCC", name: "Indonesia Kendaraan Terminal", exchange: "IDX", type: "stock" },
  { symbol: "ITIC", name: "Indonesian Tobacco", exchange: "IDX", type: "stock" },
  { symbol: "KAYU", name: "Darmi Bersaudara", exchange: "IDX", type: "stock" },
  { symbol: "KBLV", name: "First Media", exchange: "IDX", type: "stock" },
  { symbol: "KONI", name: "Perdana Bangun Pusaka", exchange: "IDX", type: "stock" },
  { symbol: "LEAD", name: "Logindo Samudramakmur", exchange: "IDX", type: "stock" },
  { symbol: "LINK", name: "Link Net", exchange: "IDX", type: "stock" },
  { symbol: "LPCK", name: "Lippo Cikarang", exchange: "IDX", type: "stock" },
  { symbol: "LTLS", name: "Lautan Luas", exchange: "IDX", type: "stock" },
  { symbol: "MDIA", name: "Intermedia Capital", exchange: "IDX", type: "stock" },
  { symbol: "META", name: "Nusantara Infrastructure", exchange: "IDX", type: "stock" },
  { symbol: "MGRO", name: "Mahkota Group", exchange: "IDX", type: "stock" },
  { symbol: "MICE", name: "Multi Indocitra", exchange: "IDX", type: "stock" },
  { symbol: "MSIN", name: "MNC Studios International", exchange: "IDX", type: "stock" },
  { symbol: "NELY", name: "Pelita Samudera Shipping", exchange: "IDX", type: "stock" },
  { symbol: "OASA", name: "Protech Mitra Perkasa", exchange: "IDX", type: "stock" },
  { symbol: "PCAR", name: "Prima Cakrawala Abadi", exchange: "IDX", type: "stock" },
  { symbol: "PJAA", name: "Pembangunan Jaya Ancol", exchange: "IDX", type: "stock" },
  { symbol: "PNBS", name: "Bank Panin Dubai Syariah", exchange: "IDX", type: "stock" },
  { symbol: "PORT", name: "Portal Asia Teknologi", exchange: "IDX", type: "stock" },
  { symbol: "REAL", name: "Repower Asia Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "SCNP", name: "Selamat Citra Nusantara Perkasa", exchange: "IDX", type: "stock" },
  { symbol: "SHIP", name: "Sillo Maritime Perdana", exchange: "IDX", type: "stock" },
  { symbol: "SLIS", name: "Gaya Abadi Sempurna", exchange: "IDX", type: "stock" },
  { symbol: "SOUL", name: "Mitra Angkasa Sejahtera", exchange: "IDX", type: "stock" },
  { symbol: "SRAJ", name: "Sejahteraraya Anugrahjaya", exchange: "IDX", type: "stock" },
  { symbol: "STTP", name: "Siantar Top", exchange: "IDX", type: "stock" },
  { symbol: "TARA", name: "Sitara Propertindo", exchange: "IDX", type: "stock" },
  { symbol: "TBLA", name: "Tunas Baru Lampung", exchange: "IDX", type: "stock" },
  { symbol: "TFAS", name: "Telefast Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "TGKA", name: "Tigaraksa Satria", exchange: "IDX", type: "stock" },
  { symbol: "TOBA", name: "TBS Energi Utama", exchange: "IDX", type: "stock" },
  { symbol: "TURI", name: "Tunas Ridean", exchange: "IDX", type: "stock" },
  { symbol: "UNIC", name: "Unggul Indah Cahaya", exchange: "IDX", type: "stock" },
  { symbol: "UNSP", name: "Bakrie Sumatra Plantations", exchange: "IDX", type: "stock" },
  { symbol: "VINS", name: "Victoria Insurance", exchange: "IDX", type: "stock" },
  { symbol: "WEGE", name: "Wijaya Karya Bangunan Gedung", exchange: "IDX", type: "stock" },
  { symbol: "WIFI", name: "Solusi Sinergi Digital", exchange: "IDX", type: "stock" },
  { symbol: "WOOD", name: "Integra Indocabinet", exchange: "IDX", type: "stock" },
  { symbol: "ZONE", name: "Mega Perintis", exchange: "IDX", type: "stock" },

  // === BATCH 2 - MORE EMITEN ===
  { symbol: "ABDA", name: "Asuransi Bina Dana Arta", exchange: "IDX", type: "stock" },
  { symbol: "ABMM", name: "ABM Investama", exchange: "IDX", type: "stock" },
  { symbol: "AGII", name: "Aneka Gas Industri", exchange: "IDX", type: "stock" },
  { symbol: "AGRS", name: "Bank IBK Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "AIMS", name: "Akbar Indo Makmur Stimec", exchange: "IDX", type: "stock" },
  { symbol: "AKSI", name: "Mineral Sumberdaya Mandiri", exchange: "IDX", type: "stock" },
  { symbol: "ALKA", name: "Alakasa Industrindo", exchange: "IDX", type: "stock" },
  { symbol: "ALMI", name: "Alumindo Light Metal Industry", exchange: "IDX", type: "stock" },
  { symbol: "AMAR", name: "Bank Amar Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "AMOR", name: "Ashmore Asset Management Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "ANJT", name: "Austindo Nusantara Jaya", exchange: "IDX", type: "stock" },
  { symbol: "ANSA", name: "Anabatic Technologies", exchange: "IDX", type: "stock" },
  { symbol: "ASGR", name: "Astra Graphia", exchange: "IDX", type: "stock" },
  { symbol: "BALI", name: "Bali Towerindo Sentra", exchange: "IDX", type: "stock" },
  { symbol: "BANK", name: "Bank Aladin Syariah", exchange: "IDX", type: "stock" },
  { symbol: "BAUT", name: "Mitra Baja Perkasa", exchange: "IDX", type: "stock" },
  { symbol: "BBMD", name: "Bank Mestika Dharma", exchange: "IDX", type: "stock" },
  { symbol: "BBSS", name: "Bumi Benowo Sukses Sejahtera", exchange: "IDX", type: "stock" },
  { symbol: "BEKS", name: "Bank Pundi Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "BEBS", name: "Berkah Beton Sadaya", exchange: "IDX", type: "stock" },
  { symbol: "BIPI", name: "Astrindo Nusantara Infrastruktur", exchange: "IDX", type: "stock" },
  { symbol: "BKDP", name: "Bukit Darmo Property", exchange: "IDX", type: "stock" },
  { symbol: "BPII", name: "Batavia Prosperindo Internasional", exchange: "IDX", type: "stock" },
  { symbol: "BTOB", name: "Cipta Selera Murni", exchange: "IDX", type: "stock" },
  { symbol: "BUVA", name: "Bukit Uluwatu Villa", exchange: "IDX", type: "stock" },
  { symbol: "CARS", name: "Industri dan Perdagangan Bintraco Dharma", exchange: "IDX", type: "stock" },
  { symbol: "CENT", name: "Centratama Telekomunikasi Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "CITY", name: "Natura City Developments", exchange: "IDX", type: "stock" },
  { symbol: "CLAY", name: "Citra Putra Realty", exchange: "IDX", type: "stock" },
  { symbol: "COCO", name: "Wahana Interfood Nusantara", exchange: "IDX", type: "stock" },
  { symbol: "DEAL", name: "Dewata Freightinternational", exchange: "IDX", type: "stock" },
  { symbol: "DEFI", name: "Dewata Finance", exchange: "IDX", type: "stock" },
  { symbol: "DRMA", name: "Dharma Polimetal", exchange: "IDX", type: "stock" },
  { symbol: "EAST", name: "Eastparc Hotel", exchange: "IDX", type: "stock" },
  { symbol: "ELPI", name: "Elang Prima Industri", exchange: "IDX", type: "stock" },
  { symbol: "EPAC", name: "Megalestari Epack Sentosajaya", exchange: "IDX", type: "stock" },
  { symbol: "ERAL", name: "Eral Energi Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "FAPA", name: "Far Pacific Prima", exchange: "IDX", type: "stock" },
  { symbol: "FLMC", name: "Falmaco Nonwoven Industri", exchange: "IDX", type: "stock" },
  { symbol: "FUJI", name: "Fuji Finance Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "GOLL", name: "Golden Plantation", exchange: "IDX", type: "stock" },
  { symbol: "GTBO", name: "Garda Tujuh Buana", exchange: "IDX", type: "stock" },
  { symbol: "GWSA", name: "Greenwood Sejahtera", exchange: "IDX", type: "stock" },
  { symbol: "HADE", name: "Himalaya Energi Perkasa", exchange: "IDX", type: "stock" },
  { symbol: "HAIS", name: "Hasnur Internasional Shipping", exchange: "IDX", type: "stock" },
  { symbol: "HRTA", name: "Hartadinata Abadi", exchange: "IDX", type: "stock" },
  { symbol: "IATA", name: "MNC Energy Investments", exchange: "IDX", type: "stock" },
  { symbol: "ICON", name: "Island Concepts Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "IFSH", name: "Ifishdeco", exchange: "IDX", type: "stock" },
  { symbol: "IPCM", name: "Jasa Armada Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "IRRA", name: "Itama Ranoraya", exchange: "IDX", type: "stock" },
  { symbol: "JARR", name: "Jaya Swarasa Agung", exchange: "IDX", type: "stock" },
  { symbol: "KIOS", name: "Kioson Komersial Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "KMDS", name: "Kurniamitra Duta Sentosa", exchange: "IDX", type: "stock" },
  { symbol: "KMTR", name: "Kirana Megatara", exchange: "IDX", type: "stock" },
  { symbol: "KOTA", name: "DMS Propertindo", exchange: "IDX", type: "stock" },
  { symbol: "KPAS", name: "Cottonindo Ariesta", exchange: "IDX", type: "stock" },
  { symbol: "LAND", name: "Trimitra Propertindo", exchange: "IDX", type: "stock" },
  { symbol: "LIFE", name: "Asuransi Jiwa Sinarmas MSIG", exchange: "IDX", type: "stock" },
  { symbol: "MARI", name: "Mas Murni Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "MCAS", name: "M Cash Integrasi", exchange: "IDX", type: "stock" },
  { symbol: "MEDS", name: "Medco Strait Singapore", exchange: "IDX", type: "stock" },
  { symbol: "MPOW", name: "Megapower Makmur", exchange: "IDX", type: "stock" },
  { symbol: "MTSM", name: "Metro Realty", exchange: "IDX", type: "stock" },
  { symbol: "NAGA", name: "Bank Mitraniaga", exchange: "IDX", type: "stock" },
  { symbol: "NASA", name: "Elang Andalan Nusantara", exchange: "IDX", type: "stock" },
  { symbol: "NATO", name: "Natura Industri Nusantara", exchange: "IDX", type: "stock" },
  { symbol: "NICK", name: "Charnic Capital", exchange: "IDX", type: "stock" },
  { symbol: "OBMD", name: "OBM Drilchem", exchange: "IDX", type: "stock" },
  { symbol: "OILS", name: "Indo Oil Perkasa", exchange: "IDX", type: "stock" },
  { symbol: "OLIV", name: "Oscar Mitra Sukses Sejahtera", exchange: "IDX", type: "stock" },
  { symbol: "PADI", name: "Minna Padi Investama", exchange: "IDX", type: "stock" },
  { symbol: "PEHA", name: "Phapros", exchange: "IDX", type: "stock" },
  { symbol: "PEVE", name: "Panca Mitra Multiperdana", exchange: "IDX", type: "stock" },
  { symbol: "PGJO", name: "Tourindo Guide Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "PNGO", name: "Pinago Utama", exchange: "IDX", type: "stock" },
  { symbol: "POLA", name: "Pool Advista Finance", exchange: "IDX", type: "stock" },
  { symbol: "PRAY", name: "Pratama Widya", exchange: "IDX", type: "stock" },
  { symbol: "PURE", name: "Triniti Dinamik", exchange: "IDX", type: "stock" },
  { symbol: "RBMS", name: "Ristia Bintang Mahkotasejati", exchange: "IDX", type: "stock" },
  { symbol: "RISE", name: "Jaya Sukses Makmur Sentosa", exchange: "IDX", type: "stock" },
  { symbol: "RMKE", name: "Respon Mulia Kencana", exchange: "IDX", type: "stock" },
  { symbol: "ROCK", name: "Rockfields Advisary", exchange: "IDX", type: "stock" },
  { symbol: "RONY", name: "Aesler Grup Internasional", exchange: "IDX", type: "stock" },
  { symbol: "RUNS", name: "Global Sukses Solusi", exchange: "IDX", type: "stock" },
  { symbol: "SAFE", name: "Steady Safe", exchange: "IDX", type: "stock" },
  { symbol: "SFAN", name: "Surya Fajar Capital", exchange: "IDX", type: "stock" },
  { symbol: "SGER", name: "Sumber Global Energy", exchange: "IDX", type: "stock" },
  { symbol: "SINI", name: "Singaraja Putra", exchange: "IDX", type: "stock" },
  { symbol: "SKRN", name: "Superkrane Mitra Utama", exchange: "IDX", type: "stock" },
  { symbol: "SNLK", name: "Sunter Lakeside Hotel", exchange: "IDX", type: "stock" },
  { symbol: "SOFA", name: "Boston Furniture Industries", exchange: "IDX", type: "stock" },
  { symbol: "SOSS", name: "Shield On Service", exchange: "IDX", type: "stock" },
  { symbol: "SWAT", name: "Sriwahana Adityakarta", exchange: "IDX", type: "stock" },
  { symbol: "TALF", name: "Tunas Alfin", exchange: "IDX", type: "stock" },
  { symbol: "TAMU", name: "Pelayaran Tamarin Samudra", exchange: "IDX", type: "stock" },
  { symbol: "TEBE", name: "Dana Brata Luhur", exchange: "IDX", type: "stock" },
  { symbol: "TECH", name: "Indosterling Technomedia", exchange: "IDX", type: "stock" },
  { symbol: "TGRA", name: "Terregra Asia Energy", exchange: "IDX", type: "stock" },
  { symbol: "TOOL", name: "Citra Maharlika Nusantara Corpora", exchange: "IDX", type: "stock" },
  { symbol: "TOYS", name: "Sunindo Adipersada", exchange: "IDX", type: "stock" },
  { symbol: "TUGU", name: "Asuransi Tugu Pratama Indonesia", exchange: "IDX", type: "stock" },
  { symbol: "UFOE", name: "Damai Sejahtera Abadi", exchange: "IDX", type: "stock" },
  { symbol: "VICO", name: "Victoria Investama", exchange: "IDX", type: "stock" },
  { symbol: "WINR", name: "Winner Nusantara Jaya", exchange: "IDX", type: "stock" },
  { symbol: "WOWS", name: "Ginting Jaya Energi", exchange: "IDX", type: "stock" },
  { symbol: "YELO", name: "Yelooo Integra Datanet", exchange: "IDX", type: "stock" },
  { symbol: "ZATA", name: "Bumi Resources Minerals", exchange: "IDX", type: "stock" },
];
